# AfnwCore2 Config File:
# AfnwCore2に関するいろんな設定を変更できるファイルです。パーミッションの設定はここでは行えません。
# 編集した後はサーバーを再起動するか、プラグインを再リロードするか、コマンド "/config_reload" を実行してください。
# デフォルト値は万が一指定されていないときにAfnwCore2が代入する値です。(World名のConfigではデフォルト値が入ってもワールドが見つからない場合はNullPointerException(例外)としてクラッシュします。)

vote: # 投票周りの設定
  item-amount: 1
  # /afnwで交換できるアイテムの数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 1
  scaffold-amount: 8
  # /afnwで交換時に一緒に配布される足場の数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 8
  ticket-amount: 1
  # 投票時に受け取れるチケットの数を指定してください。int(数)ではない場合はエラーが発生します。デフォルト: 1
  bonus-line: 10
  # 投票ボーナスの回数を指定します。指定された数以上の回数と一致したらチケット10枚とネザースターが配布されます。int(数)ではない場合はエラーが発生します。デフォルト: 10
  nether-star-amount: 1


tp:
  standby: 10
  # TPコマンド(not /tp)を使用した際の待機時間を秒で指定します。int(数)ではない場合はエラーが発生します。デフォルト: 10
  lobby_world_name: "lobby"
  # ロビーワールドの名前を指定します。デフォルト:lobby
  void_world_name: "afnw"
  # Voidワールドの名前を指定します。デフォルト:afnw
  tutorial_world_name: "tutorial"
  # チュートリアルワールドの名前を指定します。デフォルト:tutorial

afk:
  afk_world_name: "afk"
  # AFKポイントとして利用するワールド名を指定します。デフォルト:afk
  afk_point_x: 0
  afk_point_y: 0
  afk_point_z: 0
  # AFKポイントとして利用する座標をそれぞれ指定します。int(数)ではない場合はエラーが発生します。窒息を防ぐため、Y座標のみ一つ足された数値で利用されるので注意してください。
  # デフォルト値は0です。必ず指定することをおすすめします。

settings:
  player-save-period: 120
  # プレイヤーデータの自動セーブ間隔を秒で指定します。int(数)ではない場合はエラーが発生します。デフォルト: 120
  allow-wither-spawn: true
  # ウィザーのスポーン(召喚)を許可するか, booleanで指定します。 true: 許可します。召喚されてもキャンセルしません。 / false: 許可しません。召喚されてもキャンセルします。
