name: Java17 Build

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build with Java17

    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "azisabaNmsUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "azisabaNmsPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - run: ./gradlew build
